"""The PostgreSQL backend (db/pg_compat) and the connection discipline built on it.

Replaces the SQLite-era suites (pool release, engine rebind, connection
leakage, raw-file logger tests) with the same guarantees stated for the only
database the app now has: every borrowed connection goes back, a failed
statement neither poisons the connection nor blocks the next writer, the
audit trail counts what it drops, and the SQL the repositories were written
in runs unchanged.
"""

from __future__ import annotations

import sqlite3
import threading
from pathlib import Path

import pytest

from prompt_matrix.db import pg_compat


def _bind(monkeypatch, tmp_path: Path, name: str = "history.sqlite") -> None:
    """Point the process at a fresh per-test schema (derived from DATABASE_PATH)."""
    monkeypatch.setenv("DATABASE_PATH", str(tmp_path / name))
    import prompt_matrix.history as history_mod

    history_mod.DB_PATH = history_mod._resolve_db_path()


# --------------------------------------------------------------------------- #
# SQL translation (pure)
# --------------------------------------------------------------------------- #


def test_placeholders_and_percent_escaping():
    t = pg_compat.translate("SELECT x FROM t WHERE a LIKE '%foo%' AND b = ? AND c = 'it''s'", True)
    assert t.sql == "SELECT x FROM t WHERE a LIKE '%%foo%%' AND b = %s AND c = 'it''s'"
    # Without parameters psycopg does no %-formatting, so nothing is escaped.
    assert pg_compat.translate("SELECT 1 WHERE a LIKE '%x%'", False).sql == "SELECT 1 WHERE a LIKE '%x%'"


def test_ddl_types_are_rewritten_by_position_not_keyword():
    ddl = """CREATE TABLE IF NOT EXISTS t (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        score REAL,
        UNIQUE (id, timestamp)
    )"""
    out = pg_compat.translate(ddl, False).sql
    assert "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
    assert "timestamp TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP" in out  # column keeps its name
    assert "score DOUBLE PRECISION" in out
    assert "UNIQUE (id, timestamp)" in out


def test_insert_or_ignore_and_pragma_and_sqlite_master():
    assert pg_compat.translate("INSERT OR IGNORE INTO t (a) VALUES (?)", True).sql.endswith(
        "ON CONFLICT DO NOTHING"
    )
    assert "information_schema.columns" in pg_compat.translate("PRAGMA table_info(t)", False).sql
    assert pg_compat.translate("PRAGMA journal_mode=WAL;", False).sql == "SELECT 1 WHERE FALSE"
    assert "information_schema.tables" in pg_compat.translate(
        "SELECT name FROM sqlite_master WHERE type='table'", False
    ).sql


def test_schema_is_derived_per_database_path(monkeypatch):
    monkeypatch.delenv("ASSURE_PG_SCHEMA", raising=False)
    monkeypatch.setenv("ASSURE_PG_SCHEMA_FROM_DB_PATH", "1")
    a = pg_compat.current_schema("/tmp/a/history.sqlite")
    b = pg_compat.current_schema("/tmp/b/history.sqlite")
    assert a != b and a.startswith("db_") and b.startswith("db_")
    monkeypatch.setenv("ASSURE_PG_SCHEMA", "public")
    assert pg_compat.current_schema("/tmp/a/history.sqlite") == "public"


# --------------------------------------------------------------------------- #
# Live database behaviour
# --------------------------------------------------------------------------- #


def test_migrations_create_the_full_schema(tmp_path, monkeypatch):
    _bind(monkeypatch, tmp_path)
    from prompt_matrix.db.connection import _SCHEMA_VERSION, init_db
    from prompt_matrix.history import db_scope

    init_db()
    with db_scope() as db:
        version = db.execute("SELECT MAX(version) AS v FROM schema_migrations").fetchone()
        assert int(version["v"]) == _SCHEMA_VERSION
        tables = {r[0] for r in db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        assert {"projects", "jdf_revisions", "substrate_vault", "audit_log", "pipeline_cache"} <= tables
        cols = {r[1] for r in db.execute("PRAGMA table_info(substrate_vault)")}
        assert {"parser_name", "ocr_confidence", "omp_artifact_id"} <= cols


def test_timestamps_render_like_sqlite_and_lastrowid_works(tmp_path, monkeypatch):
    _bind(monkeypatch, tmp_path)
    from prompt_matrix.db.connection import init_db
    from prompt_matrix.history import db_scope

    init_db()
    with db_scope() as db:
        db.execute("INSERT INTO projects (id, title) VALUES (?, ?)", ("p1", "T"))
        row = db.execute("SELECT created_at FROM projects WHERE id = ?", ("p1",)).fetchone()
        assert len(row[0]) == 19 and row[0][10] == " "  # YYYY-MM-DD HH:MM:SS
        cur = db.execute(
            "INSERT INTO system_metrics (cpu_percent, memory_used_mb, memory_total_mb, "
            "swap_used_mb, disk_used_percent, disk_free_gb) VALUES (?,?,?,?,?,?)",
            (1, 2, 3, 4, 5, 6),
        )
        assert cur.lastrowid == 1 and cur.rowcount == 1
        db.commit()


def test_a_failed_statement_leaves_the_connection_usable(tmp_path, monkeypatch):
    """SQLite semantics kept: catch the IntegrityError, keep working on the same handle."""
    _bind(monkeypatch, tmp_path)
    from prompt_matrix.db.connection import init_db
    from prompt_matrix.history import db_scope

    init_db()
    with db_scope() as db:
        db.execute("INSERT INTO projects (id, title) VALUES (?, ?)", ("p1", "T"))
        with pytest.raises(sqlite3.IntegrityError):
            db.execute("INSERT INTO projects (id, title) VALUES (?, ?)", ("p1", "dup"))
        assert db.execute("SELECT COUNT(*) FROM projects").fetchone()[0] == 1
        db.commit()


def test_project_delete_cascades_on_a_fresh_database(tmp_path, monkeypatch):
    _bind(monkeypatch, tmp_path)
    from prompt_matrix.db.connection import init_db
    from prompt_matrix.history import db_scope

    init_db()
    with db_scope() as db:
        db.execute("INSERT INTO projects (id, title) VALUES (?, ?)", ("p1", "T"))
        db.execute(
            "INSERT INTO substrate_vault (id, project_id, filename, page_count, extracted_text) "
            "VALUES (?, ?, ?, ?, ?)",
            ("sv1", "p1", "a.pdf", 1, "text"),
        )
        db.commit()
        db.execute("DELETE FROM projects WHERE id = ?", ("p1",))
        db.commit()
        assert db.execute("SELECT COUNT(*) FROM substrate_vault").fetchone()[0] == 0


def test_borrowed_connections_are_counted_and_returned(tmp_path, monkeypatch):
    _bind(monkeypatch, tmp_path)
    from prompt_matrix.db.connection import init_db
    from prompt_matrix.db.open_connections import db_open_connection_count
    from prompt_matrix.history import borrowed_connection

    init_db()
    baseline = db_open_connection_count()
    with borrowed_connection() as conn:
        conn.execute("SELECT 1")
        assert db_open_connection_count() == baseline + 1
    assert db_open_connection_count() == baseline


def test_concurrent_writers_give_every_connection_back(tmp_path, monkeypatch):
    _bind(monkeypatch, tmp_path)
    from prompt_matrix.db.connection import init_db
    from prompt_matrix.db.open_connections import db_open_connection_count
    from prompt_matrix.history import borrowed_connection

    import gc

    init_db()
    # Handles an earlier test never closed are released by the compat
    # connection's finalizer; collect them first so the gauge below measures
    # only this test's own checkouts.
    gc.collect()
    baseline = db_open_connection_count()
    errors: list[str] = []

    def _writer(n: int) -> None:
        try:
            for i in range(5):
                with borrowed_connection() as conn:
                    conn.execute("INSERT INTO projects (id, title) VALUES (?, ?)", (f"p{n}-{i}", "T"))
                    conn.commit()
        except Exception as exc:  # pragma: no cover - reported below
            errors.append(repr(exc))

    threads = [threading.Thread(target=_writer, args=(n,)) for n in range(8)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=60)
    assert errors == []
    gc.collect()
    # No growth: every writer gave its connection back (a lower reading only
    # means another test's leftover was collected meanwhile).
    assert db_open_connection_count() <= baseline
    with borrowed_connection() as conn:
        assert conn.execute("SELECT COUNT(*) FROM projects").fetchone()[0] == 40


def test_audit_logger_writes_through_the_pool_and_counts_drops(tmp_path, monkeypatch):
    _bind(monkeypatch, tmp_path)
    from prompt_matrix.db.connection import init_db
    from prompt_matrix.db.open_connections import db_open_connection_count
    from prompt_matrix.history import borrowed_connection
    from prompt_matrix.lib.logger import AuditLogger, audit_drop_count

    init_db()
    with borrowed_connection() as conn:
        conn.execute("INSERT INTO projects (id, title) VALUES ('proj-1', 'proj-1')")
        conn.commit()
    baseline_open = db_open_connection_count()
    drops = audit_drop_count()
    audit = AuditLogger(str(tmp_path / "history.sqlite"))
    audit.log_audit("req-1", "proj-1", "INQUIRE_STREAM", success=True, duration_ms=42)
    # An unknown project is refused by the FK: counted, never raised.
    audit.log_audit("req-2", "no-such-project", "INQUIRE_STREAM", success=True)
    assert audit_drop_count() == drops + 1
    assert db_open_connection_count() == baseline_open
    with borrowed_connection() as conn:
        rows = conn.execute("SELECT request_id, success, duration_ms FROM audit_log").fetchall()
    assert [tuple(r) for r in rows] == [("req-1", 1, 42)]


def test_run_with_db_retry_retries_locked_errors():
    from prompt_matrix.db.connection import run_with_db_retry

    calls = {"n": 0}

    def flaky():
        calls["n"] += 1
        if calls["n"] < 3:
            raise sqlite3.OperationalError("database is locked")
        return "ok"

    assert run_with_db_retry(flaky, backoff_s=0.0) == "ok"
    assert calls["n"] == 3


def test_get_engine_rebinds_when_database_url_changes(monkeypatch):
    from prompt_matrix.db import pool

    pool.dispose_engine()
    url = pg_compat.database_url()
    assert url
    eng1 = pool.get_engine()
    monkeypatch.setenv("DATABASE_URL", url + ("&" if "?" in url else "?") + "application_name=rebind")
    eng2 = pool.get_engine()
    assert eng2 is not eng1
    pool.dispose_engine()
