#!/usr/bin/env bash
# Generate the repo-root .env for `docker compose up -d`.
#
#   ./scripts/gen-env.sh local   # laptop: local Ollama models, shell on 127.0.0.1
#   ./scripts/gen-env.sh ec2     # server: Bedrock through the instance IAM role,
#                                #         production flags, shell on 0.0.0.0
#
# Secrets (PEM_SECRET_KEY, ENCRYPTION_KEY, POSTGRES_PASSWORD, SHELL_ACCESS_KEY)
# are generated here. The only values you fill in by hand are the AWS ones:
# ASSURE_S3_BUCKET and AWS_DEFAULT_REGION; leave AWS_ACCESS_KEY_ID /
# AWS_SECRET_ACCESS_KEY empty when the instance has the IAM role
# (scripts/aws/iam-policy-assure-runtime.json — S3, Textract, Bedrock).
# Never commit the result; .env is gitignored. Refuses to overwrite an existing
# .env unless FORCE=1.
set -euo pipefail
TARGET="${1:-local}"
OUT="${2:-.env}"
cd "$(dirname "$0")/.."
if [[ -e "$OUT" && "${FORCE:-0}" != "1" ]]; then
  echo "$OUT exists; re-run with FORCE=1 to overwrite" >&2; exit 1
fi
rand() { openssl rand -hex "$1"; }
fernet() { python3 -c 'import base64,os;print(base64.urlsafe_b64encode(os.urandom(32)).decode())'; }

case "$TARGET" in
  ec2)
    cat > "$OUT" <<ENV
# Generated by scripts/gen-env.sh ec2 on $(date -u +%Y-%m-%dT%H:%MZ). Do not commit.
# Run: docker compose up -d      → shell http://<host>/ (port 80, key below), API 127.0.0.1:8765
# Open 80 in the security group. For TLS put a proxy / Cloudflare tunnel in front.

# ---- fill these in (only AWS values are yours) --------------------------------
ASSURE_S3_BUCKET=
AWS_DEFAULT_REGION=eu-central-1
ASSURE_S3_PREFIX=assure/
# IAM user access key with scripts/aws/iam-policy-assure-runtime.json attached
# (S3 bucket, Textract, Bedrock). Both S3 and Bedrock use this same pair.
# Leave both empty only if the instance has an IAM role instead. Never AWS_SESSION_TOKEN.
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

# ---- generated secrets --------------------------------------------------------
POSTGRES_PASSWORD=$(rand 24)
PEM_SECRET_KEY=$(rand 32)
ENCRYPTION_KEY=$(fernet)
SHELL_ACCESS_KEY=$(rand 16)

# ---- server settings ----------------------------------------------------------
ENVIRONMENT=production
ASSURE_ENV=production
APP_BIND=127.0.0.1
SHELL_BIND=0.0.0.0
SHELL_PORT=80
PORT=8765
PROXY_FIX_HOPS=1
ASSURE_REQUIRE_LOGIN=false
ASSURE_CLERK_ONLY=0
WTF_CSRF_ENABLED=0
PARSE_ASYNC=1
SUBSTRATE_ASYNC_UPLOAD=1
PARSER_SCAN_BACKEND=jdf-ocr
JDF_OCR=tesseract
ASSURE_MAX_PAGES=200
# Textract is only the fallback when OCR reads nothing; hard cap per month, list price.
ASSURE_TEXTRACT_MONTHLY_USD_CAP=100
ASSURE_TEXTRACT_MODE=detect
GUNICORN_WORKERS=2
GUNICORN_THREADS=8
WORKER_CONCURRENCY=2

# ---- models: Amazon Bedrock with the AWS credentials above (no provider key) --
ASSURE_LLM_BACKEND=bedrock
# Defaults follow AWS_DEFAULT_REGION: us./eu./apac. cross-region profiles of
# Claude Sonnet 4 (drafting, checks) and Claude 3.5 Haiku (Compare's 2nd column).
# Enable both in the Bedrock console for that region first. Override if needed:
# ASSURE_BEDROCK_MODEL=us.anthropic.claude-sonnet-4-20250514-v1:0
# ASSURE_BEDROCK_MODEL_B=us.anthropic.claude-3-5-haiku-20241022-v1:0
# Alternative: ASSURE_LLM_BACKEND= (empty) + OPENROUTER_API_KEY=... for the cloud policies.
ENV
    ;;
  local)
    cat > "$OUT" <<ENV
# Generated by scripts/gen-env.sh local on $(date -u +%Y-%m-%dT%H:%MZ). Do not commit.
# Run: docker compose up -d      → shell http://127.0.0.1:8891 (key below), API :8765
COMPOSE_PROFILES=local-llm
SHELL_ACCESS_KEY=assure-local-shell-key
PEM_SECRET_KEY=$(rand 32)
ENCRYPTION_KEY=$(fernet)
ENVIRONMENT=development
ASSURE_CLERK_ONLY=0
ASSURE_REQUIRE_LOGIN=false
WTF_CSRF_ENABLED=0
PARSE_ASYNC=1
SUBSTRATE_ASYNC_UPLOAD=1

# local models (ollama service; ~2.3 GB pulled once). Bigger = better grounding:
# qwen2.5:7b is the smallest that reliably passes the anchoring gate.
ASSURE_LLM_BACKEND=ollama
ASSURE_OLLAMA_MODEL=qwen2.5:1.5b
ASSURE_OLLAMA_MODEL_B=llama3.2:1b

# real S3 is optional locally; empty = files under ./data/objects
ASSURE_S3_BUCKET=
ASSURE_S3_PREFIX=assure/
AWS_DEFAULT_REGION=eu-central-1
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
ENV
    ;;
  *) echo "usage: $0 local|ec2 [out]" >&2; exit 2 ;;
esac
chmod 600 "$OUT"
echo "wrote $OUT ($TARGET)"
