#!/usr/bin/env python3
"""Copy an Assure SQLite database into PostgreSQL.

    DATABASE_URL=postgresql://assure:***@host:5432/assure \\
    python scripts/migrate_sqlite_to_postgres.py /app/data/history.sqlite [--truncate]

What it does, in order:

1. Runs the app's own migrations against PostgreSQL (``db.connection.init_db``
   through ``db/pg_compat``), so the target schema is exactly the one the code
   expects — the same DDL, translated.
2. Copies every table that exists on both sides, parents before children
   (projects first, then everything that references it), column by column by
   name. Columns the target does not have are skipped and reported.
3. Resets identity sequences so the next autogenerated id continues after the
   copied rows.

Row copies are batched inside one transaction per table; a table that fails
is reported and the run continues, so one bad row does not block the rest.
Re-runnable: with ``--truncate`` the target tables are emptied first; without
it, existing rows win (``ON CONFLICT DO NOTHING``).
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

#: Parents before children. Tables not listed here are copied afterwards in
#: name order; FK-referencing tables that are not listed still work because
#: every FK in the schema points at ``projects`` or ``runs``.
_ORDER = [
    "schema_migrations",
    "projects",
    "runs",
    "jdf_revisions",
    "jdf_documents",
    "jdf_cli_documents",
    "project_budgets",
    "token_ledger_entries",
    "project_templates",
    "prompts",
    "substrate_vault",
    "substrates",
    "drafts",
    "redhat_findings",
]

_SKIP = {"sqlite_sequence", "sqlite_stat1"}


def _sqlite_tables(src: sqlite3.Connection) -> list[str]:
    rows = src.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    names = [r[0] for r in rows if r[0] not in _SKIP]
    ordered = [t for t in _ORDER if t in names] + [t for t in names if t not in _ORDER]
    return ordered


def _columns(conn, table: str) -> list[str]:
    return [r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("sqlite_path")
    ap.add_argument("--truncate", action="store_true", help="empty target tables before copying")
    ap.add_argument("--batch", type=int, default=500)
    args = ap.parse_args()

    if not (os.environ.get("DATABASE_URL") or "").startswith(("postgres://", "postgresql://")):
        print("DATABASE_URL must be a postgresql:// DSN", file=sys.stderr)
        return 2
    src_path = Path(args.sqlite_path)
    if not src_path.exists():
        print(f"no such SQLite file: {src_path}", file=sys.stderr)
        return 2

    # The target must not derive a schema from DATABASE_PATH.
    os.environ.pop("ASSURE_PG_SCHEMA_FROM_DB_PATH", None)
    os.environ.setdefault("ASSURE_DATA_DIR", str(src_path.parent))

    from prompt_matrix.db.connection import init_db
    from prompt_matrix.history import db_scope

    t0 = time.time()
    init_db()
    print(f"[1/3] target schema ready ({time.time() - t0:.1f}s)")

    src = sqlite3.connect(str(src_path))
    src.row_factory = sqlite3.Row
    tables = _sqlite_tables(src)
    report: list[tuple[str, int, int, str]] = []

    with db_scope() as dst:
        dst_tables = {
            r[0] for r in dst.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
        }
        for table in tables:
            if table not in dst_tables:
                report.append((table, 0, 0, "skipped: not in target schema"))
                continue
            src_cols = _columns(src, table)
            dst_cols = set(_columns(dst, table))
            cols = [c for c in src_cols if c in dst_cols]
            missing = [c for c in src_cols if c not in dst_cols]
            total = src.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            if args.truncate:
                dst.execute(f"DELETE FROM {table}")
            placeholders = ", ".join("?" for _ in cols)
            col_list = ", ".join(f'"{c}"' for c in cols)
            insert = f"INSERT OR IGNORE INTO {table} ({col_list}) VALUES ({placeholders})"
            copied = 0
            failed = 0
            try:
                cur = src.execute(f"SELECT {', '.join(cols)} FROM {table}")
                while True:
                    batch = cur.fetchmany(args.batch)
                    if not batch:
                        break
                    for row in batch:
                        try:
                            dst.execute(insert, tuple(row))
                            copied += 1
                        except Exception as exc:  # one bad row must not stop the table
                            failed += 1
                            if failed <= 3:
                                print(f"    ! {table}: row skipped ({exc})", file=sys.stderr)
                dst.commit()
            except Exception as exc:
                dst.rollback()
                report.append((table, copied, total, f"FAILED: {exc}"))
                continue
            note = "ok" if not failed else f"{failed} row(s) skipped"
            if missing:
                note += f"; columns not in target: {', '.join(missing)}"
            report.append((table, copied, total, note))

        print("[2/3] rows copied")
        # Identity sequences: continue after the highest copied id.
        seqs = dst.execute(
            """
            SELECT table_name, column_name FROM information_schema.columns
            WHERE table_schema = current_schema() AND is_identity = 'YES'
            """
        ).fetchall()
        for table, column in seqs:
            dst.execute(
                f"SELECT setval(pg_get_serial_sequence('{table}', '{column}'), "
                f"COALESCE((SELECT MAX(\"{column}\") FROM {table}), 0) + 1, false)"
            )
        dst.commit()
        print(f"[3/3] {len(seqs)} identity sequence(s) reset")

    width = max(len(r[0]) for r in report) if report else 10
    print()
    for table, copied, total, note in report:
        print(f"  {table:<{width}}  {copied:>7}/{total:<7}  {note}")
    print(f"\ndone in {time.time() - t0:.1f}s")
    return 0 if all(not r[3].startswith("FAILED") for r in report) else 1


if __name__ == "__main__":
    raise SystemExit(main())
